#!/usr/bin/env python3
"""Prepend a new release section to CHANGELOG.md.

Reads release notes from a markdown file (typically generated by GitHub's
`/repos/{owner}/{repo}/releases/generate-notes` API) and inserts them as a
new section in CHANGELOG.md, immediately after the
`<!-- changelog-insertion-point -->` marker. The marker stays in place so
the next release can insert above the previous one, keeping CHANGELOG.md
in reverse chronological order.

Usage:
    update_changelog.py <version> <date> <notes-file>

Example:
    update_changelog.py 2.0.1 2026-05-01 release-notes.md

Behavior:
    - Errors out if CHANGELOG.md doesn't exist or has no insertion marker
    - Errors out if a section for this version already exists (idempotency
      guard so the workflow can't accidentally double-write the changelog)
    - Wraps the version in a markdown link to the GitHub release page so
      readers can jump straight to the release for downloads
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CHANGELOG = REPO / "CHANGELOG.md"
INSERTION_MARKER = "<!-- changelog-insertion-point -->"
RELEASES_URL = "https://github.com/AnyByte/LinkBridge/releases/tag"


def main() -> int:
    if len(sys.argv) != 4:
        print(__doc__, file=sys.stderr)
        return 2

    version, date, notes_path = sys.argv[1], sys.argv[2], Path(sys.argv[3])

    if not CHANGELOG.exists():
        print(f"error: {CHANGELOG} not found", file=sys.stderr)
        return 1
    if not notes_path.exists():
        print(f"error: notes file {notes_path} not found", file=sys.stderr)
        return 1

    notes = notes_path.read_text(encoding="utf-8").strip()
    if not notes:
        print(f"error: notes file {notes_path} is empty", file=sys.stderr)
        return 1

    changelog = CHANGELOG.read_text(encoding="utf-8")

    if INSERTION_MARKER not in changelog:
        print(
            f"error: insertion marker {INSERTION_MARKER!r} not found in {CHANGELOG}",
            file=sys.stderr,
        )
        return 1

    section_header = f"## [v{version}]({RELEASES_URL}/v{version}) — {date}"
    if section_header in changelog:
        print(
            f"error: section for v{version} already exists in {CHANGELOG}",
            file=sys.stderr,
        )
        return 1

    new_section = f"\n\n{section_header}\n\n{notes}\n"

    updated = changelog.replace(
        INSERTION_MARKER,
        f"{INSERTION_MARKER}{new_section}",
        1,
    )

    CHANGELOG.write_text(updated, encoding="utf-8")
    print(f"prepended v{version} section to {CHANGELOG.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
